# Generated by Django 4.2.13 on 2024-06-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombreMarca', models.CharField(default='', max_length=100, verbose_name='Marca')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'unique_together': {('nombreMarca',)},
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombrePanel', models.CharField(default='', max_length=100, verbose_name='Panel')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Panel',
                'verbose_name_plural': 'Paneles',
                'unique_together': {('nombrePanel',)},
            },
        ),
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombretv', models.CharField(default='', max_length=50, verbose_name='Televisor')),
                ('pulgadas', models.CharField(default='', max_length=50, verbose_name='Pulgadas')),
                ('resolucion', models.CharField(default='', max_length=50, verbose_name='Resolución')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='core/lineas', verbose_name='Foto')),
                ('costo', models.DecimalField(decimal_places=4, default=0, max_digits=30, verbose_name='Costo')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('marca', models.ForeignKey(blank=True, default='', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca', verbose_name='Marca')),
                ('tipoPanel', models.ForeignKey(blank=True, default='', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.panel', verbose_name='Panel')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
