# Generated by Django 4.2.13 on 2024-06-25 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_refrigeradora_costo_alter_televisor_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='marcaMicroondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('marcaMicroondas', models.CharField(default='', max_length=20, verbose_name='Marca')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'unique_together': {('marcaMicroondas',)},
            },
        ),
        migrations.CreateModel(
            name='modeloMicroondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('modelo', models.CharField(default='', max_length=20, verbose_name='Modelo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelo',
                'unique_together': {('modelo',)},
            },
        ),
        migrations.CreateModel(
            name='Microondas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombremicroondas', models.CharField(default='', max_length=20, verbose_name='Microondas')),
                ('capacidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacidad')),
                ('dimensiones', models.CharField(default='0x0x0', max_length=50, verbose_name='Dimensiones altura*hancho*profundidad')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='core/microondas', verbose_name='Foto')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Costo')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('marcaMicroondas', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marcamicroondas', verbose_name='Marca')),
                ('microondasColor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color', verbose_name='Color')),
                ('modelo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelomicroondas', verbose_name='Modelo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
